// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDomain'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDomains() {
  return window['go']['main']['App']['GetDomains']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsDaemonRunning() {
  return window['go']['main']['App']['IsDaemonRunning']();
}

export function RemoveDomain(arg1) {
  return window['go']['main']['App']['RemoveDomain'](arg1);
}

export function ScanPorts() {
  return window['go']['main']['App']['ScanPorts']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}
