// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDomain(arg1:string,arg2:number,arg3:boolean):Promise<string>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetDomains():Promise<Array<main.DomainInfo>>;

export function GetStatus():Promise<main.StatusInfo>;

export function IsDaemonRunning():Promise<boolean>;

export function RemoveDomain(arg1:string):Promise<string>;

export function SetConfig(arg1:string,arg2:string):Promise<string>;

export function StartDaemon():Promise<string>;

export function StopDaemon():Promise<string>;
